Dev
geeesy/type-interfaces pull request #158
Opened 2022-09-01 09:15 UTC by abg74123

2022-09-01 13:02 UTC, ddotx commented
อันนี้คือ field อะไร

2022-09-02 04:03 UTC, abg74123 commented
field เดิมครับเปลี่ยนชื่อเฉยๆ

2022-09-02 04:05 UTC, ddotx requested changes
อะไรที่จะเก็บเป็น timestamp ต้องใช้ชื่อห้อยว่า timestamp .... expiryDatePayment คืออะไร ถ้าจะเก็บ Date ต้องเป็น Date

2022-09-02 04:16 UTC, abg74123 commented
เก็บเป็นวันครับ 15 นาที อะไรอย่างงี้ ไม่ได้เป็น timestamp ไม่ได้เป็น date

2022-09-02 04:20 UTC, ddotx commented
> เก็บเป็นวันครับ 15 นาที อะไรอย่างงี้ ไม่ได้เป็น timestamp ไม่ได้เป็น date

ให้ใช้เป็น enum

2022-09-02 04:22 UTC, ddotx commented
ตัวอย่าง จะเป็น enum หรือ type const 

![CleanShot 2565-09-02 at 11 21 43](https://user-images.githubusercontent.com/11943914/188058417-db73c7f8-885c-4a06-bb77-066e7974b7f9.png)

2022-09-02 04:25 UTC, abg74123 commented
ผมเก็บเป็นนาทีนะครับ เช่น 12 ชั่วโมง ก็จะเก็บ 720 ต้องไปสร้าง enum เพิ่มป่าวครับ

2022-09-02 05:22 UTC, ddotx commented
> ผมเก็บเป็นนาทีนะครับ เช่น 12 ชั่วโมง ก็จะเก็บ 720 ต้องไปสร้าง enum เพิ่มป่าวครับ

ให้เก็บเป็น Const = [] เลย เช่น ExpireInMin = [720, ... ]

2022-09-02 06:06 UTC, ddotx commented
expiryOnPaymentInMin: ExpireInMin

2022-09-02 06:47 UTC, abg74123 commented
แบบนี้ป่าวครับ
![Screen Shot 2565-09-02 at 13 46 13](https://user-images.githubusercontent.com/44797554/188075441-c30211d3-cb9c-4d36-8688-b8bd1bd84ad2.png)

![Screen Shot 2565-09-02 at 13 46 29](https://user-images.githubusercontent.com/44797554/188075490-cfded445-4616-4838-acd5-9810f9ce8d03.png)

2022-09-02 09:35 UTC, ddotx approved these changes

2022-09-02 09:36 UTC, merged